- name: install mysql 
  apt: pkg={{ item }} state=latest
  with_items:
    - mysql-server-5.6
    - mysql-client-5.6

- name: copy config to remote host
  template: src=templates/config/mysql5.6/my.cnf dest=/etc/mysql/
  notify:
    - restart mysql
